stress:
  score_col: "stress_score"
  high_threshold: 6
  critical_threshold: 8

heart_rate:
  score_col: "hr"
  high_threshold: 100


time:
  start_col: "start_time"
  finish_col: "finish_time"
  start_datetime_col: "start_time_dt"
  finish_datetime_col: "finish_time_dt"
  date_col: "date"
  time_col: "time"
  hour_col: "hour"


shifts:
  shift_col: "shift"
  morning:
    label: "morning"
    start_time: "06:00"
    end_time: "14:30"

  evening:
    label: "evening"
    start_time: "14:30"
    end_time: "00:00"


data_cols:
  validation_col: "message"
  validation_choice: "SUCCESS"

data_location:
  raw_file_path: "data/raw"
  interim_file_path: "data/interim"
  processed_file_path: "data/processed"


datasets:
  user_id_col: "user_id"
  source_file_col: "source_file"
  users:
    - user_id: "user_48"
      file_name: "user_48_feb02_14_full_hrv.csv"

    - user_id: "user_49"
      file_name: "user_49_feb04_14_full_hrv_fixed.csv"

